const shopActionTypes = {
    UPDATE_COLLECTION: 'UPDATE_COLLECTION',
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAILED: 'FETCH_COLLECTION_FAILED',
}

export default shopActionTypes;